databases:
  - name: postgres
    ipAllowList: []
    databaseName: movie_review_app_render
    user: movie_review_app_render

services:
  - type: web
    name: movie_review_app_render
    env: ruby
    buildCommand: "./render-build.sh"
    startCommand: "bundle exec rails s"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: postgres
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
